### ISSUE TITLE
MISP docker issue - missing pythonlib skbuild

### ISSUE THREAD

**Issue by itzdan** [fireeye/ThreatPursuit-VM#6]
A issue was newly identified during the MISP docker setup, a missing python library Scikit-build _skbuild_ during the setup of a MISP dependency OpenCV.  This is causing the installation to exit.

The following error is observed;

```
Collecting opencv-python==4.4.0.44 (from -r REQUIREMENTS (line 56))
  Downloading https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fcrux1i_/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

**Comment by itzdan** [comment]
Adding the following Inside \web\Dockerfile manually, overcomes the missing lib and allows the installation to continue.  Attached in this ticket (rename it).

```
    pip3 install --upgrade pip setuptools wheel && \
    pip3 install scikit-build && \    
    pip3 install opencv-python && \ 
```

Will need to raise it with MISP Docker Project Team to get it formally squashed in their packages.

[Dockerfile.txt](https://github.com/fireeye/ThreatPursuit-VM/files/5487974/Dockerfile.txt)

**Comment by itzdan** [comment]
![docker all up](https://user-images.githubusercontent.com/26817824/98420598-a69a7880-20db-11eb-93ec-360f2baf8262.PNG)

**Comment by itzdan** [comment]
Have raised bug/issue in docker misp with solution.. 

https://github.com/MISP/misp-docker/issues/94
